In [1]:
import pandas as pd
pd.pandas.set_option('display.max_columns', None)

from ner_functions import get_entities_confidence_score
from faker_functions import *
from faker import Faker

In [2]:
synth = pd.read_csv('dataset/table_order.csv')

In [3]:
synth

,orderNumber,productCode,quantityOrdered,priceEach,orderLineNumber,orderDate,requiredDate,shippedDate,status,comments,customerNumber,customerName,contactLastName,contactFirstName,phone,addressLine1,addressLine2,city,state,postalCode,country,salesRepEmployeeNumber,creditLimit,productName,productLine,productScale,productVendor,productDescription,quantityInStock,buyPrice,MSRP
0,10100,S18_1749,30,136.00,3,2003-01-06,2003-01-13,2003-01-10,Shipped,NaN,363,Online Diecast Creations Co.,Young,Dorothy,6035558647,2304 Long Airport Avenue,NaN,Nashua,NH,62005,USA,1216.0,114200,*,Classic Cars,1:10,Welly Diecast Productions,*,4823.0,103.125817,213.098062
1,10100,S18_2248,50,55.09,2,2003-01-06,2003-01-13,2003-01-10,Shipped,NaN,363,Online Diecast Creations Co.,Young,Dorothy,6035558647,2304 Long Airport Avenue,NaN,Nashua,NH,62005,USA,1216.0,114200,*,Vintage Cars,1:24,Red Start Diecast,*,2728.0,15.949021,33.802497
2,10100,S18_4409,22,75.46,4,2003-01-06,2003-01-13,2003-01-10,Shipped,NaN,363,Online Diecast Creations Co.,Young,Dorothy,6035558647,2304 Long Airport Avenue,NaN,Nashua,NH,62005,USA,1216.0,114200,*,Vintage Cars,1:32,Studio M Art Models,*,2685.0,21.882745,43.659252
3,10100,S24_3969,49,35.29,1,2003-01-06,2003-01-13,2003-01-10,Shipped,NaN,363,Online Diecast Creations Co.,Young,Dorothy,6035558647,2304 Long Airport Avenue,NaN,Nashua,NH,62005,USA,1216.0,114200,*,Vintage Cars,1:32,Autoart Studio Design,*,550.0,16.061205,35.118038
4,10101,S18_2325,25,108.06,4,2003-01-09,2003-01-18,2003-01-11,Shipped,Check on availability.,128,"Blauer See Auto, Co.",Keitel,Roland,+49 69 66 90 2555,Lyonerstr. 34,NaN,Frankfurt,NaN,60528,Germany,1504.0,59700,*,Trucks and Buses,1:32,Autoart Studio Design,*,24.0,25.660152,46.427639
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2991,10425,S24_2300,49,127.79,9,2005-05-31,2005-06-07,NaN,In Process,NaN,119,La Rochelle Gifts,Labrune,Janine,40.67.8555,"67, rue des Cinquante Otages",NaN,Nantes,NaN,44000,France,1370.0,118200,*,Vintage Cars,1:18,Welly Diecast Productions,*,6763.0,71.973408,117.440000
2992,10425,S24_2840,31,31.82,5,2005-05-31,2005-06-07,NaN,In Process,NaN,119,La Rochelle Gifts,Labrune,Janine,40.67.8555,"67, rue des Cinquante Otages",NaN,Nantes,NaN,44000,France,1370.0,118200,*,Classic Cars,1:18,Gearbox Collectibles,*,9771.0,94.808700,152.250990
2993,10425,S32_1268,41,83.79,11,2005-05-31,2005-06-07,NaN,In Process,NaN,119,La Rochelle Gifts,Labrune,Janine,40.67.8555,"67, rue des Cinquante Otages",NaN,Nantes,NaN,44000,France,1370.0,118200,*,Classic Cars,1:18,Min Lin Diecast,*,9762.0,69.061199,138.994773
2994,10425,S32_2509,11,50.32,6,2005-05-31,2005-06-07,NaN,In Process,NaN,119,La Rochelle Gifts,Labrune,Janine,40.67.8555,"67, rue des Cinquante Otages",NaN,Nantes,NaN,44000,France,1370.0,118200,*,Classic Cars,1:18,Red Start Diecast,*,8909.0,93.836843,208.542691
2995,10425,S50_1392,18,94.92,2,2005-05-31,2005-06-07,NaN,In Process,NaN,119,La Rochelle Gifts,Labrune,Janine,40.67.8555,"67, rue des Cinquante Otages",NaN,Nantes,NaN,44000,France,1370.0,118200,*,Trucks and Buses,1:10,Motor City Art Classics,*,4732.0,102.752781,210.966544

In [4]:
list_entities = get_entities_confidence_score('dataset/table_order.csv')

KeyboardInterrupt:

In [4]:
list_entities

{'orderNumber': None,
 'productCode': None,
 'quantityOrdered': None,
 'priceEach': None,
 'orderLineNumber': None,
 'orderDate': {'entity': 'DATE_TIME', 'confidence_score': 1.0},
 'requiredDate': {'entity': 'DATE_TIME', 'confidence_score': 1.0},
 'shippedDate': {'entity': 'DATE_TIME', 'confidence_score': 0.97},
 'status': None,
 'comments': None,
 'customerNumber': None,
 'customerName': {'entity': 'ORGANIZATION', 'confidence_score': 0.886},
 'contactLastName': {'entity': 'PERSON', 'confidence_score': 0.526},
 'contactFirstName': {'entity': 'PERSON', 'confidence_score': 0.81},
 'phone': {'entity': 'PHONE_NUMBER', 'confidence_score': 0.592},
 'addressLine1': {'entity': 'ADDRESS', 'confidence_score': 0.592},
 'addressLine2': None,
 'city': {'entity': 'LOCATION', 'confidence_score': 0.79},
 'state': None,
 'postalCode': {'entity': 'ZIPCODE', 'confidence_score': 1.0},
 'country': {'entity': 'LOCATION', 'confidence_score': 1.0},
 'salesRepEmployeeNumber': None,
 'creditLimit': None,
 'productName': None,
 'productLine': None,
 'productScale': None,
 'productVendor': {'entity': 'ORGANIZATION', 'confidence_score': 0.428},
 'productDescription': None,
 'quantityInStock': None,
 'buyPrice': None,
 'MSRP': None}

In [6]:
get_synthetic_dataset(synth, list_entities)

Column address synthesized.
Column phone1 synthesized.
Column phone2 synthesized.
Column email synthesized.
Column first_name synthesized.
Column last_name synthesized.
Column city synthesized.
Column state synthesized.
Column web synthesized.
Column zip synthesized.
Column company_name not synthesized.
Column county not synthesized.

,first_name,last_name,company_name,address,city,county,state,zip,phone1,phone2,email,web,first_name_gender
0,Brandon,Garner,"Benton, John B Jr",8215 Greene Cape Suite 875,Lake Derekport,Orleans,VI,93522,515-529-6921x5594,487.159.4629,teresa44@gmail.com,http://pierce.biz/,male
1,Kelsey,Mays,"Chanay, Jeffrey A Esq",8452 Dalton Highway Suite 868,North Carlosshire,Livingston,AR,62606,7902639718,4894705842,xhorne@gmail.com,http://santiago.org/,female
2,Alex,Baldwin,"Chemel, James L Cpa",060 Jensen Spurs Apt. 173,Ronaldhaven,Gloucester,CO,73910,992-369-0363x40336,001-513-578-9633x698,kevinsantiago@yahoo.com,https://www.stanley.com/,male
3,Dennis,Horton,Feltz Printing Service,63169 Thomas Mission Apt. 297,Patrickmouth,Anchorage,VT,77784,164-243-6543,312.255.1466x07647,brownashley@yahoo.com,https://www.gomez.com/,unknown
4,Erica,Schmidt,Printing Dimensions,844 Amber Roads Suite 279,Perryside,Butler,WI,22459,(584)484-2347,839-655-7320,melendezryan@gmail.com,https://www.shah.com/,female
...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,Danielle,Garcia,Inner Label,392 Jeffery Lane,North Laura,Ada,KY,13796,+1-748-639-8362x697,720-580-3679x95035,brianmorris@gmail.com,https://www.hammond.org/,female
496,Rhonda,Johnson,Hermar Inc,366 Hannah Square Apt. 546,Allenland,Elkhart,ND,19817,001-514-112-5431x5488,(000)804-1014,tmoyer@yahoo.com,http://www.moore-west.info/,unknown
497,Brooke,Brown,Simonton Howe & Schneider Pc,774 Silva Route Suite 399,Angelicafurt,Box Butte,AZ,42676,(282)214-6538,001-497-240-0230,sandraharris@gmail.com,https://www.adkins.biz/,unknown
498,Christopher,Simmons,Warehouse Office & Paper Prod,29048 Lucas Junctions Apt. 922,Jacquelineshire,King,NY,59516,913.343.2598,266-463-8243x38535,hillsteven@gmail.com,http://craig.com/,male
499,Jeff,Hughes,Affiliated With Travelodge,71576 Little Street,West Juliestad,Orange,GU,15197,0863124355,(635)366-4886x24466,jay88@hotmail.com,https://jordan.com/,male

In [7]:
us_addresses= pd.read_csv("dataset/list_of_real_usa_addresses.csv")

In [8]:
us_addresses_entities = get_entities_confidence_score("dataset/list_of_real_usa_addresses.csv")

In [9]:
us_addresses_entities

{'address': {'entity': 'ADDRESS', 'confidence_score': 0.6153846153846154},
 'city': {'entity': 'LOCATION', 'confidence_score': 0.5384615384615384},
 'state': {'entity': 'LOCATION', 'confidence_score': 0.6794871794871795},
 'zip': {'entity': 'ZIPCODE', 'confidence_score': 1.0}}

In [10]:
get_synthetic_dataset(us_addresses, us_addresses_entities)

Column address synthesized.
Column city synthesized.
Column state synthesized.
Column zip synthesized.

                           address            city state    zip
0      0463 Maureen Road Suite 813   New Brianview    RI  94106
1      411 Franklin Neck Suite 103       Hollytown    MI  94060
2     524 Callahan Creek Suite 463     Diazchester    FL  38052
3               849 Kimberly Coves  South Kimberly    MS  73071
4                 8751 James Spurs    Nataliemouth    MT  19541
..                             ...             ...   ...    ...
229  612 Norton Overpass Suite 305   North Michael    ID  10814
230      491 Laurie Ferry Apt. 306     Arianahaven    MN  53967
231       568 Garza Hills Apt. 494     Michaelfort    DC  08592
232            77675 Jennifer Fork     Kristenbury    FM  35450
233    21529 Evelyn Drive Apt. 772    Lake Jeffrey    AL  81249

[234 rows x 4 columns]

In [12]:
df_creditNumber = pd.read_csv("dataset/1-MB-Test.csv")

In [13]:
df_creditNumber

      First and Last Name          SSN   Credit Card Number
0                     NaN          NaN         Visa MC AMEX
1           Robert Aragon  489-36-8350  4929-3813-3266-4295
2           Ashley Borden  514-14-8905  5370-4638-8881-3020
3           Thomas Conley  690-05-5315  4916-4811-5814-8111
4             Susan Davis  421-37-1396  4916-4034-9269-8783
...                   ...          ...                  ...
10551        Albert Iorio  322-84-2303  4916-6734-7572-5037
10552     Charles Jackson  646-44-9083  5218-0144-2703-9288
10553     Teresa Kaminski  465-73-5044  5399-0706-4128-0200
10554            Tim Lowe  044-34-6976  5144-8691-2776-1130
10555     Monte Mceachern  477-36-0304  5527-1247-5046-7802

[10556 rows x 3 columns]

In [14]:
split_name(df_creditNumber, 'First and Last Name')

               SSN   Credit Card Number first_name last_number
0              NaN         Visa MC AMEX          -           -
1      489-36-8350  4929-3813-3266-4295     Robert      Aragon
2      514-14-8905  5370-4638-8881-3020     Ashley      Borden
3      690-05-5315  4916-4811-5814-8111     Thomas      Conley
4      421-37-1396  4916-4034-9269-8783      Susan       Davis
...            ...                  ...        ...         ...
10551  322-84-2303  4916-6734-7572-5037     Albert       Iorio
10552  646-44-9083  5218-0144-2703-9288    Charles     Jackson
10553  465-73-5044  5399-0706-4128-0200     Teresa    Kaminski
10554  044-34-6976  5144-8691-2776-1130        Tim        Lowe
10555  477-36-0304  5527-1247-5046-7802      Monte   Mceachern

[10556 rows x 4 columns]

In [14]:
df_creditNumber['First and Last Name'].fillna('- -', inplace=True)
df_creditNumber['First and Last Name'].reset_index(drop=True, inplace=True)

In [15]:
lista_nomi = []
for i in df_creditNumber['First and Last Name']:
        lista_nomi.append(i.split())

In [16]:
nomi = []
cognomi = [] 
for i in lista_nomi:
     nomi.append(i[0])
     cognomi.append(i[1])

In [17]:
nomi

['-',
 'Robert',
 'Ashley',
 'Thomas',
 'Susan',
 'Christopher',
 'Rick',
 'Victor',
 'Lisa',
 'Marjorie',
 'Mark',
 'James',
 'Albert',
 'Charles',
 'Teresa',
 'Tim',
 'Monte',
 'Adriane',
 'Jerome',
 'Agnes',
 'Lynette',
 'Stacey',
 'Julie',
 'Danny',
 'Jacki',
 'Thomas',
 'Mireille',
 'Lillian',
 'Gail',
 'Johnson',
 'Rebecca',
 'Robert',
 'Ashley',
 'Thomas',
 'Susan',
 'Christopher',
 'Rick',
 'Victor',
 'Lisa',
 'Marjorie',
 'Mark',
 'James',
 'Albert',
 'Charles',
 'Teresa',
 'Tim',
 'Monte',
 'Adriane',
 'Jerome',
 'Agnes',
 'Lynette',
 'Stacey',
 'Julie',
 'Danny',
 'Jacki',
 'Thomas',
 'Mireille',
 'Lillian',
 'Gail',
 'Johnson',
 'Rebecca',
 'Robert',
 'Ashley',
 'Thomas',
 'Susan',
 'Christopher',
 'Rick',
 'Victor',
 'Lisa',
 'Marjorie',
 'Mark',
 'James',
 'Albert',
 'Charles',
 'Teresa',
 'Tim',
 'Monte',
 'Adriane',
 'Jerome',
 'Agnes',
 'Lynette',
 'Stacey',
 'Julie',
 'Danny',
 'Jacki',
 'Thomas',
 'Mireille',
 'Lillian',
 'Gail',
 'Johnson',
 'Rebecca',
 'Robert',
 'Ashley',
 'Thomas',
 'Susan',
 'Christopher',
 'Rick',
 'Victor',
 'Lisa',
 'Marjorie',
 'Mark',
 'James',
 'Albert',
 'Charles',
 'Teresa',
 'Tim',
 'Monte',
 'Adriane',
 'Jerome',
 'Agnes',
 'Lynette',
 'Stacey',
 'Julie',
 'Danny',
 'Jacki',
 'Thomas',
 'Mireille',
 'Lillian',
 'Gail',
 'Johnson',
 'Rebecca',
 'Robert',
 'Ashley',
 'Thomas',
 'Susan',
 'Christopher',
 'Rick',
 'Victor',
 'Lisa',
 'Marjorie',
 'Mark',
 'James',
 'Albert',
 'Charles',
 'Teresa',
 'Tim',
 'Monte',
 'Adriane',
 'Jerome',
 'Agnes',
 'Lynette',
 'Stacey',
 'Julie',
 'Danny',
 'Jacki',
 'Thomas',
 'Mireille',
 'Lillian',
 'Gail',
 'Johnson',
 'Rebecca',
 'Robert',
 'Ashley',
 'Thomas',
 'Susan',
 'Christopher',
 'Rick',
 'Victor',
 'Lisa',
 'Marjorie',
 'Mark',
 'James',
 'Albert',
 'Charles',
 'Teresa',
 'Tim',
 'Monte',
 'Adriane',
 'Jerome',
 'Agnes',
 'Lynette',
 'Stacey',
 'Julie',
 'Danny',
 'Jacki',
 'Thomas',
 'Mireille',
 'Lillian',
 'Gail',
 'Johnson',
 'Rebecca',
 'Robert',
 'Ashley',
 'Thomas',
 'Susan',
 'Christopher',
 'Rick',
 'Victor',
 'Lisa',
 'Marjorie',
 'Mark',
 'James',
 'Albert',
 'Charles',
 'Teresa',
 'Tim',
 'Monte',
 'Adriane',
 'Jerome',
 'Agnes',
 'Lynette',
 'Stacey',
 'Julie',
 'Danny',
 'Jacki',
 'Thomas',
 'Mireille',
 'Lillian',
 'Gail',
 'Johnson',
 'Rebecca',
 'Robert',
 'Ashley',
 'Thomas',
 'Susan',
 'Christopher',
 'Rick',
 'Victor',
 'Lisa',
 'Marjorie',
 'Mark',
 'James',
 'Albert',
 'Charles',
 'Teresa',
 'Tim',
 'Monte',
 'Adriane',
 'Jerome',
 'Agnes',
 'Lynette',
 'Stacey',
 'Julie',
 'Danny',
 'Jacki',
 'Thomas',
 'Mireille',
 'Lillian',
 'Gail',
 'Johnson',
 'Rebecca',
 'Robert',
 'Ashley',
 'Thomas',
 'Susan',
 'Christopher',
 'Rick',
 'Victor',
 'Lisa',
 'Marjorie',
 'Mark',
 'James',
 'Albert',
 'Charles',
 'Teresa',
 'Tim',
 'Monte',
 'Adriane',
 'Jerome',
 'Agnes',
 'Lynette',
 'Stacey',
 'Julie',
 'Danny',
 'Jacki',
 'Thomas',
 'Mireille',
 'Lillian',
 'Gail',
 'Johnson',
 'Rebecca',
 'Robert',
 'Ashley',
 'Thomas',
 'Susan',
 'Christopher',
 'Rick',
 'Victor',
 'Lisa',
 'Marjorie',
 'Mark',
 'James',
 'Albert',
 'Charles',
 'Teresa',
 'Tim',
 'Monte',
 'Adriane',
 'Jerome',
 'Agnes',
 'Lynette',
 'Stacey',
 'Julie',
 'Danny',
 'Jacki',
 'Thomas',
 'Mireille',
 'Lillian',
 'Gail',
 'Johnson',
 'Rebecca',
 'Robert',
 'Ashley',
 'Thomas',
 'Susan',
 'Christopher',
 'Rick',
 'Victor',
 'Lisa',
 'Marjorie',
 'Mark',
 'James',
 'Albert',
 'Charles',
 'Teresa',
 'Tim',
 'Monte',
 'Adriane',
 'Jerome',
 'Agnes',
 'Lynette',
 'Stacey',
 'Julie',
 'Danny',
 'Jacki',
 'Thomas',
 'Mireille',
 'Lillian',
 'Gail',
 'Johnson',
 'Rebecca',
 'Robert',
 'Ashley',
 'Thomas',
 'Susan',
 'Christopher',
 'Rick',
 'Victor',
 'Lisa',
 'Marjorie',
 'Mark',
 'James',
 'Albert',
 'Charles',
 'Teresa',
 'Tim',
 'Monte',
 'Adriane',
 'Jerome',
 'Agnes',
 'Lynette',
 'Stacey',
 'Julie',
 'Danny',
 'Jacki',
 'Thomas',
 'Mireille',
 'Lillian',
 'Gail',
 'Johnson',
 'Rebecca',
 'Robert',
 'Ashley',
 'Thomas',
 'Susan',
 'Christopher',
 'Rick',
 'Victor',
 'Lisa',
 'Marjorie',
 'Mark',
 'James',
 'Albert',
 'Charles',
 'Teresa',
 'Tim',
 'Monte',
 'Adriane',
 'Jerome',
 'Agnes',
 'Lynette',
 'Stacey',
 'Julie',
 'Danny',
 'Jacki',
 'Thomas',
 'Mireille',
 'Lillian',
 'Gail',
 'Johnson',
 'Rebecca',
 'Robert',
 'Ashley',
 'Thomas',
 'Susan',
 'Christopher',
 'Rick',
 'Victor',
 'Lisa',
 'Marjorie',
 'Mark',
 'James',
 'Albert',
 'Charles',
 'Teresa',
 'Tim',
 'Monte',
 'Adriane',
 'Jerome',
 'Agnes',
 'Lynette',
 'Stacey',
 'Julie',
 'Danny',
 'Jacki',
 'Thomas',
 'Mireille',
 'Lillian',
 'Gail',
 'Johnson',
 'Rebecca',
 'Robert',
 'Ashley',
 'Thomas',
 'Susan',
 'Christopher',
 'Rick',
 'Victor',
 'Lisa',
 'Marjorie',
 'Mark',
 'James',
 'Albert',
 'Charles',
 'Teresa',
 'Tim',
 'Monte',
 'Adriane',
 'Jerome',
 'Agnes',
 'Lynette',
 'Stacey',
 'Julie',
 'Danny',
 'Jacki',
 'Thomas',
 'Mireille',
 'Lillian',
 'Gail',
 'Johnson',
 'Rebecca',
 'Robert',
 'Ashley',
 'Thomas',
 'Susan',
 'Christopher',
 'Rick',
 'Victor',
 'Lisa',
 'Marjorie',
 'Mark',
 'James',
 'Albert',
 'Charles',
 'Teresa',
 'Tim',
 'Monte',
 'Adriane',
 'Jerome',
 'Agnes',
 'Lynette',
 'Stacey',
 'Julie',
 'Danny',
 'Jacki',
 'Thomas',
 'Mireille',
 'Lillian',
 'Gail',
 'Johnson',
 'Rebecca',
 'Robert',
 'Ashley',
 'Thomas',
 'Susan',
 'Christopher',
 'Rick',
 'Victor',
 'Lisa',
 'Marjorie',
 'Mark',
 'James',
 'Albert',
 'Charles',
 'Teresa',
 'Tim',
 'Monte',
 'Adriane',
 'Jerome',
 'Agnes',
 'Lynette',
 'Stacey',
 'Julie',
 'Danny',
 'Jacki',
 'Thomas',
 'Mireille',
 'Lillian',
 'Gail',
 'Johnson',
 'Rebecca',
 'Robert',
 'Ashley',
 'Thomas',
 'Susan',
 'Christopher',
 'Rick',
 'Victor',
 'Lisa',
 'Marjorie',
 'Mark',
 'James',
 'Albert',
 'Charles',
 'Teresa',
 'Tim',
 'Monte',
 'Adriane',
 'Jerome',
 'Agnes',
 'Lynette',
 'Stacey',
 'Julie',
 'Danny',
 'Jacki',
 'Thomas',
 'Mireille',
 'Lillian',
 'Gail',
 'Johnson',
 'Rebecca',
 'Robert',
 'Ashley',
 'Thomas',
 'Susan',
 'Christopher',
 'Rick',
 'Victor',
 'Lisa',
 'Marjorie',
 'Mark',
 'James',
 'Albert',
 'Charles',
 'Teresa',
 'Tim',
 'Monte',
 'Adriane',
 'Jerome',
 'Agnes',
 'Lynette',
 'Stacey',
 'Julie',
 'Danny',
 'Jacki',
 'Thomas',
 'Mireille',
 'Lillian',
 'Gail',
 'Johnson',
 'Rebecca',
 'Robert',
 'Ashley',
 'Thomas',
 'Susan',
 'Christopher',
 'Rick',
 'Victor',
 'Lisa',
 'Marjorie',
 'Mark',
 'James',
 'Albert',
 'Charles',
 'Teresa',
 'Tim',
 'Monte',
 'Adriane',
 'Jerome',
 'Agnes',
 'Lynette',
 'Stacey',
 'Julie',
 'Danny',
 'Jacki',
 'Thomas',
 'Mireille',
 'Lillian',
 'Gail',
 'Johnson',
 'Rebecca',
 'Robert',
 'Ashley',
 'Thomas',
 'Susan',
 'Christopher',
 'Rick',
 'Victor',
 'Lisa',
 'Marjorie',
 'Mark',
 'James',
 'Albert',
 'Charles',
 'Teresa',
 'Tim',
 'Monte',
 'Adriane',
 'Jerome',
 'Agnes',
 'Lynette',
 'Stacey',
 'Julie',
 'Danny',
 'Jacki',
 'Thomas',
 'Mireille',
 'Lillian',
 'Gail',
 'Johnson',
 'Rebecca',
 'Robert',
 'Ashley',
 'Thomas',
 'Susan',
 'Christopher',
 'Rick',
 'Victor',
 'Lisa',
 'Marjorie',
 'Mark',
 'James',
 'Albert',
 'Charles',
 'Teresa',
 'Tim',
 'Monte',
 'Adriane',
 'Jerome',
 'Agnes',
 'Lynette',
 'Stacey',
 'Julie',
 'Danny',
 'Jacki',
 'Thomas',
 'Mireille',
 'Lillian',
 'Gail',
 'Johnson',
 'Rebecca',
 'Robert',
 'Ashley',
 'Thomas',
 'Susan',
 'Christopher',
 'Rick',
 'Victor',
 'Lisa',
 'Marjorie',
 'Mark',
 'James',
 'Albert',
 'Charles',
 'Teresa',
 'Tim',
 'Monte',
 'Adriane',
 'Jerome',
 'Agnes',
 'Lynette',
 'Stacey',
 'Julie',
 'Danny',
 'Jacki',
 'Thomas',
 'Mireille',
 'Lillian',
 'Gail',
 'Johnson',
 'Rebecca',
 'Robert',
 'Ashley',
 'Thomas',
 'Susan',
 'Christopher',
 'Rick',
 'Victor',
 'Lisa',
 'Marjorie',
 'Mark',
 'James',
 'Albert',
 'Charles',
 'Teresa',
 'Tim',
 'Monte',
 'Adriane',
 'Jerome',
 'Agnes',
 'Lynette',
 'Stacey',
 'Julie',
 'Danny',
 'Jacki',
 'Thomas',
 'Mireille',
 'Lillian',
 'Gail',
 'Johnson',
 'Rebecca',
 'Robert',
 'Ashley',
 'Thomas',
 'Susan',
 'Christopher',
 'Rick',
 'Victor',
 'Lisa',
 'Marjorie',
 'Mark',
 'James',
 'Albert',
 'Charles',
 'Teresa',
 'Tim',
 'Monte',
 'Adriane',
 'Jerome',
 'Agnes',
 'Lynette',
 'Stacey',
 'Julie',
 'Danny',
 'Jacki',
 'Thomas',
 'Mireille',
 'Lillian',
 'Gail',
 'Johnson',
 'Rebecca',
 'Robert',
 'Ashley',
 'Thomas',
 'Susan',
 'Christopher',
 'Rick',
 'Victor',
 'Lisa',
 'Marjorie',
 'Mark',
 'James',
 'Albert',
 'Charles',
 'Teresa',
 'Tim',
 'Monte',
 'Adriane',
 'Jerome',
 'Agnes',
 'Lynette',
 'Stacey',
 'Julie',
 'Danny',
 'Jacki',
 'Thomas',
 'Mireille',
 'Lillian',
 'Gail',
 'Johnson',
 'Rebecca',
 'Robert',
 'Ashley',
 'Thomas',
 'Susan',
 'Christopher',
 'Rick',
 'Victor',
 'Lisa',
 'Marjorie',
 'Mark',
 'James',
 'Albert',
 'Charles',
 'Teresa',
 'Tim',
 'Monte',
 'Adriane',
 'Jerome',
 'Agnes',
 'Lynette',
 'Stacey',
 'Julie',
 'Danny',
 'Jacki',
 'Thomas',
 'Mireille',
 'Lillian',
 'Gail',
 'Johnson',
 'Rebecca',
 'Robert',
 'Ashley',
 'Thomas',
 'Susan',
 'Christopher',
 'Rick',
 'Victor',
 'Lisa',
 'Marjorie',
 'Mark',
 'James',
 'Albert',
 'Charles',
 'Teresa',
 'Tim',
 'Monte',
 'Adriane',
 'Jerome',
 'Agnes',
 'Lynette',
 'Stacey',
 'Julie',
 'Danny',
 'Jacki',
 'Thomas',
 'Mireille',
 'Lillian',
 'Gail',
 'Johnson',
 'Rebecca',
 'Robert',
 'Ashley',
 'Thomas',
 'Susan',
 'Christopher',
 'Rick',
 'Victor',
 'Lisa',
 'Marjorie',
 'Mark',
 'James',
 'Albert',
 'Charles',
 'Teresa',
 'Tim',
 'Monte',
 'Adriane',
 'Jerome',
 'Agnes',
 'Lynette',
 'Stacey',
 'Julie',
 'Danny',
 'Jacki',
 'Thomas',
 'Mireille',
 'Lillian',
 'Gail',
 'Johnson',
 'Rebecca',
 'Robert',
 'Ashley',
 'Thomas',
 'Susan',
 'Christopher',
 'Rick',
 'Victor',
 'Lisa',
 'Marjorie',
 'Mark',
 'James',
 'Albert',
 'Charles',
 'Teresa',
 'Tim',
 'Monte',
 'Adriane',
 'Jerome',
 'Agnes',
 'Lynette',
 'Stacey',
 'Julie',
 'Danny',
 'Jacki',
 'Thomas',
 'Mireille',
 'Lillian',
 'Gail',
 'Johnson',
 'Rebecca',
 'Robert',
 'Ashley',
 'Thomas',
 'Susan',
 'Christopher',
 'Rick',
 'Victor',
 'Lisa',
 'Marjorie',
 'Mark',
 'James',
 'Albert',
 'Charles',
 'Teresa',
 'Tim',
 'Monte',
 'Adriane',
 'Jerome',
 'Agnes',
 'Lynette',
 'Stacey',
 'Julie',
 'Danny',
 'Jacki',
 'Thomas',
 'Mireille',
 'Lillian',
 'Gail',
 'Johnson',
 'Rebecca',
 'Robert',
 'Ashley',
 'Thomas',
 'Susan',
 'Christopher',
 'Rick',
 'Victor',
 'Lisa',
 'Marjorie',
 'Mark',
 'James',
 'Albert',
 'Charles',
 'Teresa',
 'Tim',
 'Monte',
 'Adriane',
 'Jerome',
 'Agnes',
 'Lynette',
 'Stacey',
 'Julie',
 'Danny',
 'Jacki',
 'Thomas',
 'Mireille',
 'Lillian',
 'Gail',
 'Johnson',
 'Rebecca',
 'Robert',
 'Ashley',
 'Thomas',
 'Susan',
 'Christopher',
 'Rick',
 'Victor',
 'Lisa',
 'Marjorie',
 'Mark',
 'James',
 'Albert',
 'Charles',
 'Teresa',
 'Tim',
 'Monte',
 'Adriane',
 'Jerome',
 'Agnes',
 'Lynette',
 'Stacey',
 'Julie',
 'Danny',
 'Jacki',
 'Thomas',
 'Mireille',
 'Lillian',
 'Gail',
 'Johnson',
 'Rebecca',
 'Robert',
 'Ashley',
 'Thomas',
 'Susan',
 'Christopher',
 'Rick',
 'Victor',
 'Lisa',
 'Marjorie',
 ...]

In [18]:
df_creditNumber['first_name'] = pd.Series(nomi)
df_creditNumber['last_name'] = pd.Series(cognomi)

In [19]:
df_creditNumber = df_creditNumber.drop('First and Last Name', axis = 1)

In [20]:
df_creditNumber.to_csv('dataset/1-MB-test-modified.csv', index=False)

In [11]:
df_creditNumber = pd.read_csv('dataset/1-MB-test-modified.csv')

In [7]:
df_creditNumber

               SSN   Credit Card Number first_name  last_name
0              NaN         Visa MC AMEX          -          -
1      489-36-8350  4929-3813-3266-4295     Robert     Aragon
2      514-14-8905  5370-4638-8881-3020     Ashley     Borden
3      690-05-5315  4916-4811-5814-8111     Thomas     Conley
4      421-37-1396  4916-4034-9269-8783      Susan      Davis
...            ...                  ...        ...        ...
10551  322-84-2303  4916-6734-7572-5037     Albert      Iorio
10552  646-44-9083  5218-0144-2703-9288    Charles    Jackson
10553  465-73-5044  5399-0706-4128-0200     Teresa   Kaminski
10554  044-34-6976  5144-8691-2776-1130        Tim       Lowe
10555  477-36-0304  5527-1247-5046-7802      Monte  Mceachern

[10556 rows x 4 columns]

In [12]:
list_credit_entities = get_entities_confidence_score('dataset/1-MB-test-modified.csv')

In [13]:
list_credit_entities

{'SSN': {'entity': 'US_SSN', 'confidence_score': 0.918},
 'Credit Card Number': {'entity': 'CREDIT_CARD_NUMBER',
  'confidence_score': 1.0},
 'first_name': {'entity': 'PERSON', 'confidence_score': 0.9},
 'last_name': {'entity': 'PERSON', 'confidence_score': 0.484}}

In [14]:
get_synthetic_dataset(df_creditNumber, list_credit_entities)

Column first_name synthesized.
Column last_name synthesized.
Column Credit Card Number synthesized.
Column SSN synthesized.

               SSN Credit Card Number first_name  last_name first_name_gender
0      625-49-2269      4733911104117      Kevin      Colon           unknown
1      511-35-3470       630441343963      Malik      Frost              male
2      298-73-4065    345470422801166     Kendra  Rasmussen     mostly_female
3      643-35-5910     30206907475989       Kyle     Thomas              male
4      128-22-4901   4025116269490857     Monica    Herrera            female
...            ...                ...        ...        ...               ...
10551  485-65-0365       502004571688    Jeffery       Rich              male
10552  847-73-9561    376988579517295       Ryan    Coleman              male
10553  234-48-2209   3500167966533610     Tracey   Santiago            female
10554  415-15-6928      4156849299272  Nathaniel     Palmer              male
10555  353-32-6360     30149213398265      Jacob      Simon              male

[10556 rows x 5 columns]

In [6]:
full_noia = pd.read_csv('dataset/full-foia-contacts.csv')

In [7]:
full_noia

,Agency,Department,Name,Title,Room Number,Street Address,City,State,Zip Code,Telephone,Fax,Email Address,Website,Online Request Form,Notes
0,Agricultural Marketing Service,Department of Agriculture,Gregory Bridges,FOIA Officer,"AG Stop 0202, Room 3521-S","1400 Independence Avenue, SW",Washington,DC,20250-0273,(202) 720-2498,(202) 690-3767,AMS.FOIA@USDA.gov,http://www.ams.usda.gov/about-ams/foia,NaN,NaN
1,Agricultural Marketing Service,Department of Agriculture,NaN,FOIA Requester Service Center,NaN,NaN,NaN,NaN,NaN,(202) 720-2498,NaN,NaN,NaN,NaN,NaN
2,Agricultural Marketing Service,Department of Agriculture,William Allen,FOIA Public Liaison,"AG Stop 0202, Room 3521-S","1400 Independence Avenue, SW",Washington,DC,20250-0273,(202) 720-2498,NaN,AMS.FOIA@USDA.gov,NaN,NaN,NaN
3,Animal & Plant Health Inspection,Department of Agriculture,Tonya Woods,FOIA Director,Unit 50,4700 River Road,Riverdale,MD,20737-1232,(301) 851-4102,(301) 734-5941,mailto:tonya.g.woods@aphis.usda.gov,http://www.aphis.usda.gov/wps/portal/aphis/res...,http://www.aphis.usda.gov/wps/portal/aphis/res...,NaN
4,Animal & Plant Health Inspection,Department of Agriculture,NaN,FOIA Requester Service Center,NaN,NaN,NaN,NaN,NaN,(301) 851-4102,(301) 734-5941,mailto:foia.officer@aphis.usda.gov,NaN,NaN,* Please mail requests to FOIA.Officer@aphis.u...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
742,Office of Small and Disadvantaged Business Uti...,Department of Veterans Affairs,NaN,FOIA Requester Service Center,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
743,Office of Small and Disadvantaged Business Uti...,Department of Veterans Affairs,James Horan,FOIA Public Liaison,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
744,I don't know which office,Department of Veterans Affairs,Laurie Karnay,FOIA Team Lead,(005R1C) VACO,"810 Vermont Avenue, NW",Washington,DC,20420,(202) 632-7465,(202) 632-7581,NaN,http://www.foia.va.gov/,NaN,NaN
745,I don't know which office,Department of Veterans Affairs,NaN,FOIA Requester Service Center,NaN,NaN,NaN,NaN,NaN,(202) 632-7600,NaN,NaN,NaN,NaN,NaN
746,I don't know which office,Department of Veterans Affairs,NaN,FOIA Public Liaison,NaN,NaN,NaN,NaN,NaN,(202) 632-7600,NaN,NaN,NaN,NaN,NaN

In [8]:
split_name(full_noia, 'Name')

,Agency,Department,Title,Room Number,Street Address,City,State,Zip Code,Telephone,Fax,Email Address,Website,Online Request Form,Notes,first_name,last_number
0,Agricultural Marketing Service,Department of Agriculture,FOIA Officer,"AG Stop 0202, Room 3521-S","1400 Independence Avenue, SW",Washington,DC,20250-0273,(202) 720-2498,(202) 690-3767,AMS.FOIA@USDA.gov,http://www.ams.usda.gov/about-ams/foia,NaN,NaN,Gregory,Bridges
1,Agricultural Marketing Service,Department of Agriculture,FOIA Requester Service Center,NaN,NaN,NaN,NaN,NaN,(202) 720-2498,NaN,NaN,NaN,NaN,NaN,-,-
2,Agricultural Marketing Service,Department of Agriculture,FOIA Public Liaison,"AG Stop 0202, Room 3521-S","1400 Independence Avenue, SW",Washington,DC,20250-0273,(202) 720-2498,NaN,AMS.FOIA@USDA.gov,NaN,NaN,NaN,William,Allen
3,Animal & Plant Health Inspection,Department of Agriculture,FOIA Director,Unit 50,4700 River Road,Riverdale,MD,20737-1232,(301) 851-4102,(301) 734-5941,mailto:tonya.g.woods@aphis.usda.gov,http://www.aphis.usda.gov/wps/portal/aphis/res...,http://www.aphis.usda.gov/wps/portal/aphis/res...,NaN,Tonya,Woods
4,Animal & Plant Health Inspection,Department of Agriculture,FOIA Requester Service Center,NaN,NaN,NaN,NaN,NaN,(301) 851-4102,(301) 734-5941,mailto:foia.officer@aphis.usda.gov,NaN,NaN,* Please mail requests to FOIA.Officer@aphis.u...,-,-
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
742,Office of Small and Disadvantaged Business Uti...,Department of Veterans Affairs,FOIA Requester Service Center,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-,-
743,Office of Small and Disadvantaged Business Uti...,Department of Veterans Affairs,FOIA Public Liaison,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,James,Horan
744,I don't know which office,Department of Veterans Affairs,FOIA Team Lead,(005R1C) VACO,"810 Vermont Avenue, NW",Washington,DC,20420,(202) 632-7465,(202) 632-7581,NaN,http://www.foia.va.gov/,NaN,NaN,Laurie,Karnay
745,I don't know which office,Department of Veterans Affairs,FOIA Requester Service Center,NaN,NaN,NaN,NaN,NaN,(202) 632-7600,NaN,NaN,NaN,NaN,NaN,-,-
746,I don't know which office,Department of Veterans Affairs,FOIA Public Liaison,NaN,NaN,NaN,NaN,NaN,(202) 632-7600,NaN,NaN,NaN,NaN,NaN,-,-

In [30]:
lista_nomi = []
for i in full_noia['Name']:
        lista_nomi.append(i.split())

In [31]:
for i in lista_nomi:
    if len(i) < 2:
        i.append('-')

In [32]:
nomi = []
cognomi = [] 
for i in lista_nomi:
     nomi.append(i[0])
     cognomi.append(i[1])

In [33]:
full_noia['first_name'] = pd.Series(nomi)
full_noia['last_name'] = pd.Series(cognomi)

In [34]:
full_noia

,Agency,Department,Name,Title,Room Number,Street Address,City,State,Zip Code,Telephone,Fax,Email Address,Website,Online Request Form,Notes,first_name,last_name
0,Agricultural Marketing Service,Department of Agriculture,Gregory Bridges,FOIA Officer,"AG Stop 0202, Room 3521-S","1400 Independence Avenue, SW",Washington,DC,20250-0273,(202) 720-2498,(202) 690-3767,AMS.FOIA@USDA.gov,http://www.ams.usda.gov/about-ams/foia,NaN,NaN,Gregory,Bridges
1,Agricultural Marketing Service,Department of Agriculture,- -,FOIA Requester Service Center,NaN,NaN,NaN,NaN,NaN,(202) 720-2498,NaN,NaN,NaN,NaN,NaN,-,-
2,Agricultural Marketing Service,Department of Agriculture,William Allen,FOIA Public Liaison,"AG Stop 0202, Room 3521-S","1400 Independence Avenue, SW",Washington,DC,20250-0273,(202) 720-2498,NaN,AMS.FOIA@USDA.gov,NaN,NaN,NaN,William,Allen
3,Animal & Plant Health Inspection,Department of Agriculture,Tonya Woods,FOIA Director,Unit 50,4700 River Road,Riverdale,MD,20737-1232,(301) 851-4102,(301) 734-5941,mailto:tonya.g.woods@aphis.usda.gov,http://www.aphis.usda.gov/wps/portal/aphis/res...,http://www.aphis.usda.gov/wps/portal/aphis/res...,NaN,Tonya,Woods
4,Animal & Plant Health Inspection,Department of Agriculture,- -,FOIA Requester Service Center,NaN,NaN,NaN,NaN,NaN,(301) 851-4102,(301) 734-5941,mailto:foia.officer@aphis.usda.gov,NaN,NaN,* Please mail requests to FOIA.Officer@aphis.u...,-,-
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
742,Office of Small and Disadvantaged Business Uti...,Department of Veterans Affairs,- -,FOIA Requester Service Center,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-,-
743,Office of Small and Disadvantaged Business Uti...,Department of Veterans Affairs,James Horan,FOIA Public Liaison,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,James,Horan
744,I don't know which office,Department of Veterans Affairs,Laurie Karnay,FOIA Team Lead,(005R1C) VACO,"810 Vermont Avenue, NW",Washington,DC,20420,(202) 632-7465,(202) 632-7581,NaN,http://www.foia.va.gov/,NaN,NaN,Laurie,Karnay
745,I don't know which office,Department of Veterans Affairs,- -,FOIA Requester Service Center,NaN,NaN,NaN,NaN,NaN,(202) 632-7600,NaN,NaN,NaN,NaN,NaN,-,-
746,I don't know which office,Department of Veterans Affairs,- -,FOIA Public Liaison,NaN,NaN,NaN,NaN,NaN,(202) 632-7600,NaN,NaN,NaN,NaN,NaN,-,-

In [35]:
full_noia = full_noia.drop('Name', axis = 1)

In [5]:
full_noia.to_csv('dataset/full-noia-contacts-modified.csv', index=False)

In [2]:
full_noia = pd.read_csv('dataset/full-noia-contacts-modified.csv')

In [9]:
list_full_entities = get_entities_confidence_score('dataset/full-noia-contacts-modified.csv')

In [10]:
list_full_entities

{'Agency': {'entity': 'ORGANIZATION', 'confidence_score': 0.884},
 'Department': {'entity': 'ORGANIZATION', 'confidence_score': 1.0},
 'Name': {'entity': 'PERSON', 'confidence_score': 0.63},
 'Title': {'entity': 'PERSON', 'confidence_score': 0.332},
 'Room Number': {'entity': 'ORGANIZATION', 'confidence_score': 0.154},
 'Street Address': None,
 'City': {'entity': 'LOCATION', 'confidence_score': 0.33},
 'State': None,
 'Zip Code': {'entity': 'ZIPCODE', 'confidence_score': 1.0},
 'Telephone': {'entity': 'PHONE_NUMBER', 'confidence_score': 0.9},
 'Fax': {'entity': 'PHONE_NUMBER', 'confidence_score': 0.334},
 'Email Address': {'entity': 'EMAIL_ADDRESS', 'confidence_score': 0.408},
 'Website': {'entity': 'URL', 'confidence_score': 0.348},
 'Online Request Form': None,
 'Notes': {'entity': 'ORGANIZATION', 'confidence_score': 0.14},
 'first_name': {'entity': 'PERSON', 'confidence_score': 0.532},
 'last_number': None}

In [11]:
get_synthetic_dataset(full_noia, list_full_entities)

Column Telephone synthesized.
Column Fax synthesized.
Column Email Address synthesized.
Column first_name synthesized.
Column City synthesized.
Column Website synthesized.
Column Zip Code synthesized.
Column Room Number not synthesized.
Column Notes not synthesized.
Column Agency not synthesized.
Column Department not synthesized.
Column Name not synthesized.
Column Title not synthesized.

,Agency,Department,Name,Title,Room Number,Street Address,City,State,Zip Code,Telephone,Fax,Email Address,Website,Online Request Form,Notes,first_name,last_number,first_name_gender
0,Agricultural Marketing Service,Department of Agriculture,Gregory Bridges,FOIA Officer,"AG Stop 0202, Room 3521-S","1400 Independence Avenue, SW",West Teresa,DC,99207,273-567-9943,001-128-201-8863x2179,fkaufman@gmail.com,http://www.bowman-sullivan.com/,NaN,NaN,Benjamin,Bridges,male
1,Agricultural Marketing Service,Department of Agriculture,- -,FOIA Requester Service Center,NaN,NaN,Simmonsmouth,NaN,74553,499-234-6613x123,(666)346-6886,raymond69@gmail.com,https://www.fisher.biz/,NaN,NaN,James,-,unknown
2,Agricultural Marketing Service,Department of Agriculture,William Allen,FOIA Public Liaison,"AG Stop 0202, Room 3521-S","1400 Independence Avenue, SW",West Sandra,DC,06338,877.190.4642,001-717-848-5404,melissathomas@hotmail.com,https://www.obrien.info/,NaN,NaN,Timothy,Allen,male
3,Animal & Plant Health Inspection,Department of Agriculture,Tonya Woods,FOIA Director,Unit 50,4700 River Road,Lake Dustinchester,MD,53627,(306)453-3610x467,+1-458-893-6375x31956,jjimenez@yahoo.com,https://www.burns.org/,http://www.aphis.usda.gov/wps/portal/aphis/res...,NaN,Kathryn,Woods,female
4,Animal & Plant Health Inspection,Department of Agriculture,- -,FOIA Requester Service Center,NaN,NaN,Port Kaylaland,NaN,57045,003.412.6234,554-188-1404,hernandezmarcia@gmail.com,https://larsen.biz/,NaN,* Please mail requests to FOIA.Officer@aphis.u...,Brandon,-,unknown
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
742,Office of Small and Disadvantaged Business Uti...,Department of Veterans Affairs,- -,FOIA Requester Service Center,NaN,NaN,Lake Ashleymouth,NaN,97490,(500)754-3308x51486,579-375-6150x966,clinemegan@gmail.com,https://www.stone-brown.com/,NaN,NaN,Paula,-,unknown
743,Office of Small and Disadvantaged Business Uti...,Department of Veterans Affairs,James Horan,FOIA Public Liaison,NaN,NaN,Port Michael,NaN,22165,(404)916-1845x7900,7857836243,elizabethparker@yahoo.com,https://holden.biz/,NaN,NaN,Timothy,Horan,male
744,I don't know which office,Department of Veterans Affairs,Laurie Karnay,FOIA Team Lead,(005R1C) VACO,"810 Vermont Avenue, NW",Lake Laurie,DC,38317,603.522.6082x8280,(759)147-5123,katelynnelson@gmail.com,https://patterson.biz/,NaN,NaN,Emily,Karnay,female
745,I don't know which office,Department of Veterans Affairs,- -,FOIA Requester Service Center,NaN,NaN,Christopherbury,NaN,82083,+1-012-419-5842x5886,(372)059-9171x7908,hwhitaker@yahoo.com,https://www.brennan.com/,NaN,NaN,Jodi,-,unknown
746,I don't know which office,Department of Veterans Affairs,- -,FOIA Public Liaison,NaN,NaN,Petersonfurt,NaN,78017,170-926-6486x3998,5663096924,lisa71@yahoo.com,http://www.bradshaw.com/,NaN,NaN,Julie,-,unknown

In [4]:
df= pd.read_csv("dataset/contact_list_Austin.csv")

In [5]:
df

,Department,First Name,Last Name,Primary Contact,E-Mail Address,Phone Number,Role
0,Department,First Name,Last Name,Primary Contact,E-Mail Address,Phone Number,Role
1,Animal Services Office,Joan,Hamilton-Huber,NaN,Joan.Hamilton-Huber@austintexas.gov,512-978-0538,NaN
2,Austin Code Department,Nathan,Brigmon,NaN,Nathan.Brigmon@austintexas.gov,512-974-6533,Liaison
3,Austin Code Department,Shawn,Lincoln,NaN,Shawn.Lincoln@austintexas.gov,512-974-9029,NaN
4,Austin Convention Center,Chris,Hernandez,NaN,Chris.Hernandez@austintexas.gov,512-404-4031,Liaison
...,...,...,...,...,...,...,...
139,Austin Resource Recovery,Thomas,Montgomery,No,Thomas.Montgomery@austintexas.gov,512-974-6022,Publisher
140,Austin Resource Recovery,Thomas,Montgomery,No,Thomas.Montgomery@austintexas.gov,512-974-6022,Publisher
141,Homeland Security and Emergency Management,Angel,Flores,Yes,Angel.flores@austintexas.gov,512-974-0477,Liaison
142,Office of the City Auditor,Tyler,Myers,Yes,Tyler.Myers@austintexas.gov,512-974-2015,Liaison
143,Austin Transportation Department,Diana,Martin,Yes,Diana.Martin@austintexas.gov,512-974-4079,Liaison

In [6]:
list_df_entities = get_entities_confidence_score('dataset/contact_list_Austin.csv')

In [8]:
list_df_entities

{'Department': {'entity': 'ORGANIZATION',
  'confidence_score': 0.8611111111111112},
 'First Name': {'entity': 'PERSON', 'confidence_score': 0.7777777777777778},
 'Last Name': {'entity': 'PERSON', 'confidence_score': 0.4027777777777778},
 'Primary Contact': None,
 'E-Mail Address': {'entity': 'EMAIL_ADDRESS',
  'confidence_score': 0.8888888888888888},
 'Phone Number': {'entity': 'PHONE_NUMBER',
  'confidence_score': 0.8611111111111112},
 'Role': None}

In [7]:
get_synthetic_dataset(df, list_df_entities)

Column Phone Number synthesized.
Column E-Mail Address synthesized.
Column First Name synthesized.
Column Last Name synthesized.
Column Department not synthesized.

,Department,First Name,Last Name,Primary Contact,E-Mail Address,Phone Number,Role,first_name_gender
0,Department,Casey,Clark,Primary Contact,shelby56@gmail.com,(059)632-2714x9372,Role,unknown
1,Animal Services Office,Samantha,Boyd,NaN,jameslisa@hotmail.com,001-310-813-7700x23658,NaN,female
2,Austin Code Department,Gregory,Clark,NaN,wolfebrett@gmail.com,(173)461-9218x90076,Liaison,male
3,Austin Code Department,Derek,Shaffer,NaN,ajones@yahoo.com,766.551.9286x65944,NaN,mostly_male
4,Austin Convention Center,Michael,Marshall,NaN,scastillo@hotmail.com,001-066-732-9165x6185,Liaison,mostly_male
...,...,...,...,...,...,...,...,...
139,Austin Resource Recovery,Jeffrey,Lawrence,No,melanie82@hotmail.com,9115360689,Publisher,male
140,Austin Resource Recovery,Thomas,Jones,No,phillipsalas@hotmail.com,907-860-8093x176,Publisher,male
141,Homeland Security and Emergency Management,Andrew,Spencer,Yes,nathan23@gmail.com,294.542.8449,Liaison,male
142,Office of the City Auditor,Michael,Robinson,Yes,gonzalezcolleen@yahoo.com,(311)325-8720x73990,Liaison,mostly_male
143,Austin Transportation Department,Michele,Sanchez,Yes,jamesriggs@hotmail.com,+1-718-754-4968x37639,Liaison,female

In [2]:
df_table_order = pd.read_csv("dataset/table_order.csv")

In [3]:
df_table_order

,orderNumber,productCode,quantityOrdered,priceEach,orderLineNumber,orderDate,requiredDate,shippedDate,status,comments,customerNumber,customerName,contactLastName,contactFirstName,phone,addressLine1,addressLine2,city,state,postalCode,country,salesRepEmployeeNumber,creditLimit,productName,productLine,productScale,productVendor,productDescription,quantityInStock,buyPrice,MSRP
0,10100,S18_1749,30,136.00,3,2003-01-06,2003-01-13,2003-01-10,Shipped,NaN,363,Online Diecast Creations Co.,Young,Dorothy,6035558647,2304 Long Airport Avenue,NaN,Nashua,NH,62005,USA,1216.0,114200,*,Classic Cars,1:10,Welly Diecast Productions,*,4823.0,103.125817,213.098062
1,10100,S18_2248,50,55.09,2,2003-01-06,2003-01-13,2003-01-10,Shipped,NaN,363,Online Diecast Creations Co.,Young,Dorothy,6035558647,2304 Long Airport Avenue,NaN,Nashua,NH,62005,USA,1216.0,114200,*,Vintage Cars,1:24,Red Start Diecast,*,2728.0,15.949021,33.802497
2,10100,S18_4409,22,75.46,4,2003-01-06,2003-01-13,2003-01-10,Shipped,NaN,363,Online Diecast Creations Co.,Young,Dorothy,6035558647,2304 Long Airport Avenue,NaN,Nashua,NH,62005,USA,1216.0,114200,*,Vintage Cars,1:32,Studio M Art Models,*,2685.0,21.882745,43.659252
3,10100,S24_3969,49,35.29,1,2003-01-06,2003-01-13,2003-01-10,Shipped,NaN,363,Online Diecast Creations Co.,Young,Dorothy,6035558647,2304 Long Airport Avenue,NaN,Nashua,NH,62005,USA,1216.0,114200,*,Vintage Cars,1:32,Autoart Studio Design,*,550.0,16.061205,35.118038
4,10101,S18_2325,25,108.06,4,2003-01-09,2003-01-18,2003-01-11,Shipped,Check on availability.,128,"Blauer See Auto, Co.",Keitel,Roland,+49 69 66 90 2555,Lyonerstr. 34,NaN,Frankfurt,NaN,60528,Germany,1504.0,59700,*,Trucks and Buses,1:32,Autoart Studio Design,*,24.0,25.660152,46.427639
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2991,10425,S24_2300,49,127.79,9,2005-05-31,2005-06-07,NaN,In Process,NaN,119,La Rochelle Gifts,Labrune,Janine,40.67.8555,"67, rue des Cinquante Otages",NaN,Nantes,NaN,44000,France,1370.0,118200,*,Vintage Cars,1:18,Welly Diecast Productions,*,6763.0,71.973408,117.440000
2992,10425,S24_2840,31,31.82,5,2005-05-31,2005-06-07,NaN,In Process,NaN,119,La Rochelle Gifts,Labrune,Janine,40.67.8555,"67, rue des Cinquante Otages",NaN,Nantes,NaN,44000,France,1370.0,118200,*,Classic Cars,1:18,Gearbox Collectibles,*,9771.0,94.808700,152.250990
2993,10425,S32_1268,41,83.79,11,2005-05-31,2005-06-07,NaN,In Process,NaN,119,La Rochelle Gifts,Labrune,Janine,40.67.8555,"67, rue des Cinquante Otages",NaN,Nantes,NaN,44000,France,1370.0,118200,*,Classic Cars,1:18,Min Lin Diecast,*,9762.0,69.061199,138.994773
2994,10425,S32_2509,11,50.32,6,2005-05-31,2005-06-07,NaN,In Process,NaN,119,La Rochelle Gifts,Labrune,Janine,40.67.8555,"67, rue des Cinquante Otages",NaN,Nantes,NaN,44000,France,1370.0,118200,*,Classic Cars,1:18,Red Start Diecast,*,8909.0,93.836843,208.542691
2995,10425,S50_1392,18,94.92,2,2005-05-31,2005-06-07,NaN,In Process,NaN,119,La Rochelle Gifts,Labrune,Janine,40.67.8555,"67, rue des Cinquante Otages",NaN,Nantes,NaN,44000,France,1370.0,118200,*,Trucks and Buses,1:10,Motor City Art Classics,*,4732.0,102.752781,210.966544

In [4]:
list_df_table_order_entities = get_entities_confidence_score('dataset/table_order.csv')

In [5]:
list_df_table_order_entities

{'orderNumber': None,
 'productCode': None,
 'quantityOrdered': None,
 'priceEach': None,
 'orderLineNumber': None,
 'orderDate': {'entity': 'DATE_TIME', 'confidence_score': 1.0},
 'requiredDate': {'entity': 'DATE_TIME', 'confidence_score': 1.0},
 'shippedDate': {'entity': 'DATE_TIME', 'confidence_score': 0.95},
 'status': None,
 'comments': None,
 'customerNumber': None,
 'customerName': {'entity': 'ORGANIZATION', 'confidence_score': 0.882},
 'contactLastName': {'entity': 'PERSON', 'confidence_score': 0.536},
 'contactFirstName': {'entity': 'PERSON', 'confidence_score': 0.816},
 'phone': {'entity': 'PHONE_NUMBER', 'confidence_score': 0.574},
 'addressLine1': {'entity': 'ADDRESS', 'confidence_score': 0.538},
 'addressLine2': None,
 'city': {'entity': 'LOCATION', 'confidence_score': 0.78},
 'state': None,
 'postalCode': {'entity': 'ZIPCODE', 'confidence_score': 1.0},
 'country': {'entity': 'LOCATION', 'confidence_score': 1.0},
 'salesRepEmployeeNumber': None,
 'creditLimit': None,
 'productName': None,
 'productLine': None,
 'productScale': None,
 'productVendor': {'entity': 'ORGANIZATION', 'confidence_score': 0.456},
 'productDescription': None,
 'quantityInStock': None,
 'buyPrice': None,
 'MSRP': None}

In [6]:
get_synthetic_dataset(df_table_order, list_df_table_order_entities)

Column addressLine1 synthesized.
Column phone synthesized.
Column contactFirstName synthesized.
Column contactLastName synthesized.
Column city synthesized.
Column postalCode synthesized.
Column country synthesized.
Column orderDate not synthesized.
Column requiredDate not synthesized.
Column shippedDate not synthesized.
Column customerName not synthesized.
Column productVendor not synthesized.

,orderNumber,productCode,quantityOrdered,priceEach,orderLineNumber,orderDate,requiredDate,shippedDate,status,comments,customerNumber,customerName,contactLastName,contactFirstName,phone,addressLine1,addressLine2,city,state,postalCode,country,salesRepEmployeeNumber,creditLimit,productName,productLine,productScale,productVendor,productDescription,quantityInStock,buyPrice,MSRP,first_name_gender
0,10100,S18_1749,30,136.00,3,2003-01-06,2003-01-13,2003-01-10,Shipped,NaN,363,Online Diecast Creations Co.,Cuevas,Tiffany,(869)381-4786,0823 Wilson Mews Suite 212,NaN,Newmanhaven,NH,68284,Netherlands Antilles,1216.0,114200,*,Classic Cars,1:10,Welly Diecast Productions,*,4823.0,103.125817,213.098062,female
1,10100,S18_2248,50,55.09,2,2003-01-06,2003-01-13,2003-01-10,Shipped,NaN,363,Online Diecast Creations Co.,Davis,Jasmine,(275)991-1174x673,9438 Martinez Radial Suite 198,NaN,Stephenborough,NH,93462,Greece,1216.0,114200,*,Vintage Cars,1:24,Red Start Diecast,*,2728.0,15.949021,33.802497,female
2,10100,S18_4409,22,75.46,4,2003-01-06,2003-01-13,2003-01-10,Shipped,NaN,363,Online Diecast Creations Co.,Mccarty,Kimberly,9934748202,1988 Robinson Grove Apt. 888,NaN,Kathleenview,NH,94362,United States Minor Outlying Islands,1216.0,114200,*,Vintage Cars,1:32,Studio M Art Models,*,2685.0,21.882745,43.659252,female
3,10100,S24_3969,49,35.29,1,2003-01-06,2003-01-13,2003-01-10,Shipped,NaN,363,Online Diecast Creations Co.,Smith,Breanna,(007)888-5752,65754 Kennedy Garden Apt. 384,NaN,West Michellefurt,NH,73843,South Africa,1216.0,114200,*,Vintage Cars,1:32,Autoart Studio Design,*,550.0,16.061205,35.118038,female
4,10101,S18_2325,25,108.06,4,2003-01-09,2003-01-18,2003-01-11,Shipped,Check on availability.,128,"Blauer See Auto, Co.",Mathis,Ian,477-231-7444,353 Mcneil Lane Suite 313,NaN,North Joshua,NaN,04294,Czech Republic,1504.0,59700,*,Trucks and Buses,1:32,Autoart Studio Design,*,24.0,25.660152,46.427639,male
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2991,10425,S24_2300,49,127.79,9,2005-05-31,2005-06-07,NaN,In Process,NaN,119,La Rochelle Gifts,Blackburn,Andrew,059-866-8813x234,6615 Swanson Mills,NaN,Emilytown,NaN,36440,Uganda,1370.0,118200,*,Vintage Cars,1:18,Welly Diecast Productions,*,6763.0,71.973408,117.440000,unknown
2992,10425,S24_2840,31,31.82,5,2005-05-31,2005-06-07,NaN,In Process,NaN,119,La Rochelle Gifts,Hamilton,Mckenzie,+1-500-852-8931x9788,86886 Lopez Turnpike Suite 781,NaN,Lake Katherinefurt,NaN,71481,Slovenia,1370.0,118200,*,Classic Cars,1:18,Gearbox Collectibles,*,9771.0,94.808700,152.250990,unknown
2993,10425,S32_1268,41,83.79,11,2005-05-31,2005-06-07,NaN,In Process,NaN,119,La Rochelle Gifts,Gomez,Brenda,(569)907-7609,751 Angela Rapids Suite 167,NaN,Kristinton,NaN,30199,Cyprus,1370.0,118200,*,Classic Cars,1:18,Min Lin Diecast,*,9762.0,69.061199,138.994773,unknown
2994,10425,S32_2509,11,50.32,6,2005-05-31,2005-06-07,NaN,In Process,NaN,119,La Rochelle Gifts,Martin,Dawn,(845)194-5875x63449,28246 Steven Island,NaN,Shorthaven,NaN,04237,Northern Mariana Islands,1370.0,118200,*,Classic Cars,1:18,Red Start Diecast,*,8909.0,93.836843,208.542691,unknown
2995,10425,S50_1392,18,94.92,2,2005-05-31,2005-06-07,NaN,In Process,NaN,119,La Rochelle Gifts,Dunlap,Erika,001-206-358-5791,11709 Vaughn Brooks,NaN,Port Michaelmouth,NaN,76222,South Georgia and the South Sandwich Islands,1370.0,118200,*,Trucks and Buses,1:10,Motor City Art Classics,*,4732.0,102.752781,210.966544,unknown

In [3]:
from faker_generator import FakerGenerator

In [4]:
df = pd.read_csv('dataset/PersonalInfo.csv')

In [5]:
list_entities = get_entities_confidence_score('dataset/PersonalInfo.csv')

In [6]:
faker_generator = FakerGenerator(df, list_entities)

In [7]:
faker_generator.get_columns_with_assigned_entity()

In [8]:
faker_generator.get_address()

In [9]:
faker_generator.get_phone_number()

In [11]:
faker_generator.get_first_name()

In [12]:
faker_generator.get_last_name()

In [13]:
faker_generator.get_columns_not_synthesized()

In [14]:
faker_generator.synthesis_message()

Column address synthesized.
Column phone1 synthesized.
Column phone2 synthesized.
Column first_name synthesized.
Column last_name synthesized.
Column company_name not synthesized.
Column city not synthesized.
Column county not synthesized.
Column state not synthesized.
Column zip not synthesized.
Column email not synthesized.
Column web not synthesized.

In [7]:
faker_generator.get_faker_generation()

Column address synthesized.
Column phone1 synthesized.
Column phone2 synthesized.
Column email synthesized.
Column first_name synthesized.
Column last_name synthesized.
Column city synthesized.
Column state synthesized.
Column web synthesized.
Column zip synthesized.
Column company_name not synthesized.
Column county not synthesized.

In [8]:
df

,first_name,last_name,company_name,address,city,county,state,zip,phone1,phone2,email,web,first_name_gender
0,Justin,Morgan,"Benton, John B Jr",4088 Thompson Lodge Apt. 536,Welchland,Orleans,WI,77984,4093195683,001-583-261-3037x864,brian98@yahoo.com,https://www.miller-cook.org/,male
1,Jennifer,Stephenson,"Chanay, Jeffrey A Esq",813 Kristen Lodge Apt. 424,Lake Barryshire,Livingston,ME,86181,(319)745-5810x85097,+1-118-776-5267x68977,qfoley@gmail.com,https://mcmahon-hodge.org/,female
2,Paul,Wilson,"Chemel, James L Cpa",9166 Smith Walk,Port Davidberg,Gloucester,FL,59796,397.588.0309x4787,008-867-9853,amykrueger@hotmail.com,http://hines.net/,male
3,Daniel,Mcintosh,Feltz Printing Service,3857 Parker Corners,South Catherinemouth,Anchorage,IA,50728,(899)746-3299,185.456.7613x59152,gardnerkimberly@yahoo.com,http://hale-brooks.com/,unknown
4,Kathryn,Nash,Printing Dimensions,871 Johnson Prairie Suite 040,Amandaview,Butler,MI,80045,+1-571-438-2662x13052,165.648.6646,kwilliams@gmail.com,https://www.curtis.org/,female
...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,Danielle,Blair,Inner Label,5992 Megan Trail,East Caitlin,Ada,WA,88858,8777744499,(779)330-8548,jonathan49@yahoo.com,http://www.thompson.biz/,female
496,Taylor,May,Hermar Inc,85397 John Junction Suite 756,Smithmouth,Elkhart,CO,26224,(143)037-6706x94141,+1-384-882-5373x0031,johnsongary@hotmail.com,https://www.hernandez.com/,unknown
497,Kimberly,Miller,Simonton Howe & Schneider Pc,5505 William Shore,Lake Judith,Box Butte,VA,89024,698.360.3646,215-376-0008x651,wrightsamuel@gmail.com,https://www.green-taylor.com/,unknown
498,Christopher,Lawrence,Warehouse Office & Paper Prod,9775 Richard Rapids Suite 515,Port Feliciaville,King,AS,93997,+1-317-303-6172x58021,826.236.5493x34020,jacksonryan@gmail.com,http://www.taylor-davidson.org/,male
499,Kenneth,Davis,Affiliated With Travelodge,907 Christina Radial,Kristaville,Orange,VT,27892,477-442-9329x028,(570)108-4025x74204,kyle75@yahoo.com,https://mora.com/,male

In [6]:
from faker import Faker

if len(list_entities) > 0:
    try:
        faker = Faker()
        loc_cols = [[i, list_entities[i]['entity']] for i in list_entities if list_entities[i] is not None]
        
        adrs = [i[0] for i in loc_cols if i[1] == 'ADDRESS']
        for i in adrs:
            synth[i] = [faker.street_address() for i in range(synth.shape[0])]

        phone = [i[0] for i in loc_cols if i[1] == 'PHONE_NUMBER']
        for i in phone:
            synth[i] = [faker.phone_number() for i in range(synth.shape[0])]

        
    except:
        print('Something went wrong while create fake PIIs')